@api = http://localhost:3000/personas

GET {{api}}


###
POST {{api}}
Content-Type: application/json

{
    "nombre" : "uto",
    "pais": "españa"
}

###
GET {{api}}/2


###
PUT {{api}}/1529hswkt0b078
Content-Type: application/json

{
    "nombre" : "Augusto",
    "pais": "españa"
}

###
DELETE {{api}}/4051mw1akssehwdn